
###
POST   http://localhost:4000/employee-api/employees
Content-Type: application/json

{
  "name": "Boss",
  "email": "boss@gmail.com",
  "mobile": "9999999999",
  "designation": "Manager",
  "companyName": "ABC Pvt Ltd"
}

###
GET    http://localhost:4000/employee-api/employees

###
PUT    http://localhost:4000/employee-api/employees/

###
DELETE http://localhost:4000/employee-api/employees/69ca1d49e01cf03e0c454c78